name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-arm:
    name: Test on ARM
    runs-on: ubicloud-standard-2-arm
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y --no-install-recommends gcc clang llvm libbpf0 libbpf-dev musl musl-dev build-essential linux-libc-dev linux-tools-common

      - name: Create links
        run: |
          sudo ln -s /usr/include/aarch64-linux-gnu/asm /usr/include/asm
          sudo ln -s /usr/include/aarch64-linux-gnu/bits /usr/include/bits
          sudo ln -s /usr/include/aarch64-linux-gnu/sys /usr/include/sys
          sudo ln -s /usr/include/aarch64-linux-gnu/gnu /usr/include/gnu

      - name: Check system
        run: |
          uname -a
          lscpu
          ip a
          ifconfig

      - name: Build
        run: make build

      - name: Debug
        run: |
          sudo ./build/durdur attach -i ens3
          timeout 20s sudo cat /sys/kernel/debug/tracing/trace_pipe > trace_output.txt &
          timeout 20s sudo tcpdump -i ens3 -nn > tcp_output.txt &
          sudo ./build/durdur drop --src "169.155.49.112"
          ping -c 1 -I ens3 169.155.49.112 || true
          sudo bpftool map list
          sudo ip a
          sudo ip link show
          sudo ip link show dev ens3
          sudo bpftool prog show
          sudo bpftool net show
          sudo dmesg | tail -n 50
          sudo ./build/durdur detach
          sleep 20s
          cat trace_output.txt
          cat tcp_output.txt
          echo "ok"
          

      - name: Test
        run: make test
