name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-arm:
    name: Test on ARM
    runs-on: ubicloud-standard-2-arm
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y --no-install-recommends gcc clang llvm libbpf0 libbpf-dev musl musl-dev build-essential linux-libc-dev

      - name: Create links
        run: |
          sudo ln -s /usr/include/aarch64-linux-gnu/asm /usr/include/asm
          sudo ln -s /usr/include/aarch64-linux-gnu/bits /usr/include/bits
          sudo ln -s /usr/include/aarch64-linux-gnu/sys /usr/include/sys
          sudo ln -s /usr/include/aarch64-linux-gnu/gnu /usr/include/gnu

      - name: Check system
        run: |
          uname -a
          lscpu
          ip a
          ifconfig

      - name: Generate
        run: make generate

      - name: Test
        run: make test
